apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: "{{ .Values.container.image }}:{{ .Values.deployment.tag }}"
        ports:
        - containerPort: {{ .Values.container.port }}
      imagePullSecrets:
        - name: recrec
